### PR TITLE
specifying which IP is to be used for virtualized Windows host file

### PR DESCRIPTION
**Pull request by Pinolo**

### CODE REVIEW

**Comment by paolomainardi** [comment]
Thanks.

**Comment by paolomainardi** [comment]
Can you provide an example ?

**Comment by paolomainardi** [comment]
ping

**Comment by Pinolo** [comment]
Maybe we're better off simply saying how the user can obtain the IP (e.g. using ping?)

**Comment by stickgrinder** [comment]
I'd go with you idea @Pinolo, can you please address this so we'll merge this one? Thanks and sorry for the very, very late review.

**Comment by Pinolo** [comment]
Should be complete, now

**Pull request merged**
