### PR TITLE
refs #114: Add Universal Definition of Done

### PR DESCRIPTION
**Pull request by paolomainardi**

### CODE REVIEW

**Comment by stickgrinder** [comment]
@paolomainardi great work! I'd like to ask:

1. Is it worth to mention technical or non technical documentation as a part of the DoD, when relevant to the issue?
2. Should we add a "project-level" DoD which defines which qualities a project as a whole should have to be considered "production-ready"? It should come from applying this "local" DoD but there may be aspects that are at a higher level and should be taken into account as a whole before declaring a project is over. This may inform the measurement of progress throughout the development too.

**Comment by stickgrinder** [comment]
**Point 1: About the documentation**

I'm actually thinking broadly about stuff like:

* Fixtures to perform QA / Smoke Tests (fake accounts for different roles, complete/partial/wrong items already available in the DB, mocked information, etc)
* Accounts, small guides, information for dev/staging/test environments of related services we may depend upon (i.e. we integrate an upstream or downstream services and we want to access it to check everything is working during development, etc)
* Architectural schemas, overviews, domain terms explanations
* Technical and business key contacts

In short I'm thinking all the information a new dev or a tester getting to the project actually need to work flawlessly and without keeping asking around for information that are given for granted.

**Point 2: about project-level provisions**

I wrote in a vary bad way. What I mean is this. The DoD you proposed contains a (very!) valuable set of provisions that are common to every contribution, in every project, so they are "controbution-level" provisions.
What I think we may add is a short set of policies for the _whole project_ to be considered _done_. For example:

* The project can be built locally by running "make" on a correctly provisioned machine
* All the operations to deploy the project to non-local environments are automated and don't depend on manual task or personal knowledge
* All information to access the environments are properly documented
* No mock or half-baked feature is deployed to the staging environment
* ...

Those are not well formulated and are out the top of my head. Also I understand that most of that is a natural consequence of the DOD you wrote.

Still I think, out of our previous experience, that a "last day of the project" checklist, that encompasses the whole set of qualities a DONE project must have, may be helpful to guide the various stages of development and say if the project is actually done.

Hope I didn't make "more mess" :)

**Comment by paolomainardi** [comment]
Thanks @stickgrinder, for the very good suggestions; I'll work on them during the Christmas holiday break :)

**Comment by paolomainardi** [comment]
Working the other comments here: https://github.com/sparkfabrik/company-playbook/pull/128/files

**Pull request merged**
